### ISSUE TITLE
Smoking in IPCI

### ISSUE THREAD

**Issue by ericaVoss** [mi-erasmusmc/ETL-IPCI#1]
I see one IPCI code mapped to smoking: `'P17.00'-Tabaksmisbruik`, which is mapped to `437264`.  

But when I look for `'% roken%'` in the OBSERVATION table I find records not mapped to any concepts.  I think there is an opportunity to add some additional mappings in.

```{SQL}
SELECT DISTINCT OBSERVATION_CONCEPT_ID, OBSERVATION_SOURCE_VALUE
FROM OBSERVATION
WHERE OBSERVATION_SOURCE_VALUE LIKE '% roken%'
```

```{TEXT}
CONCEPT_ID;OBSERVATION_SOURCE_VALUE
0;"SRDAAQ|Local|Gestopt met roken sinds"
0;"RSTOPQ|PROM|Stopdatum roken"
```

**Comment by PRijnbeek** [comment]
When I look at the frequency most is about advise of stopping.
The start age of smoking could be one to add but this is probably a guess from the patient.
Stop date we could possibly.

For the replication we have to see what the impact really is, it al depends on if this was taken into account when extracting on the original dataset.

 | Code | Text | System | Count | 
------------ | -------------| -------------| -------------
 | ADMIAQ | Advies stoppen met roken gegeven | WCIA26 | 185392 | 
 | RSTAPQ | Startleeftijd roken | PROM | 14322 | 
 | RSTOPQ | Stopdatum roken | PROM | 9292 | 
 | 210 | Stoppen met roken | LOC | 803 | 
 | BRSRAQ | Belangrijkste reden stoppen met roken | WCIA2 | 443 | 
 | SR10 | Status van stop roken | LOC | 315 | 
 | SR4 | Medicatie voor stop roken? | LOC | 302 | 
 | ADVMEDSR | Medicatie stop roken | LOC | 274 | 
 | SR6 | Medicatie stop roken | LOC | 180 | 
 | 2913 | Bent u gestopt met roken? | LOC | 140 | 
 | SMRZ1 | Hoe oud was u toen u begon met roken | PROT | 67 | 
 | 2911 | Functie van roken voor u | LOC | 65 | 
 | SMRLAATST | Laatste poging stop roken | PROT | 63 | 
 | 1072 | Bent u gestopt met roken? | LOC | 61 | 
 | 2918 | Plan (stoppen roken begeleidin | LOC | 55 | 
 | 1052 | Functie van roken voor u | LOC | 44 | 
 | 1077 | Plan (stoppen roken begeleidin | LOC | 36 | 
 | SRRZPZ | Reden geen geregelde zorg (stop roken) | LOC | 30 | 
 | ROKEN-PASS | Passief roken | LOC | 29 | 
 | 1070 | Functie van roken voor u | LOC | 25 | 
 | 970 | Functie van roken voor u | LOC | 21 | 
 | 1516 | Bent u gestopt met roken? | LOC | 20 | 
 | 1521 | Plan (stoppen roken begeleidin | LOC | 17 | 
 | ROABAQ | Aard bijwerking(en) medic(stoppen roken) | WC | 12 | 
 | LCIT0012 | is patiënt gestopt met roken? | WCIA26 | 10 | 
 | 2919 | Nog steeds gestopt met roken | LOC | 8 | 
 | ROKSTOASCO | Gestopt met roken | LOC | 8 | 
 | 2316 | Functie van roken voor u | LOC | 8 | 
 | 1328 | Functie van roken voor u | LOC | 8 | 
 | 1514 | Functie van roken voor u | LOC | 7 | 
 |  | gestopt met roken | LOC | 6 | 
 | 1580 | Bent u gestopt met roken? | LOC | 5 | 
 | Stoppe | Stoppen met roken | LOC | 4 | 
 | 1054 | Bent u gestopt met roken? | LOC | 3 | 
 | 1474 | Functie van roken voor u | LOC | 3 | 
 | 969 | Functie van roken voor u | LOC | 3 | 
 | 1059 | Plan (stoppen roken begeleidin | LOC | 2 | 
 | 2318 | Bent u gestopt met roken? | LOC | 2 | 
 | 1612 | Wilt u stoppen met roken? | LOC | 2 | 
 | 2210 | Stoppen met roken | LOC | 2 | 
 | 1611 | De nadelen van roken besproken | LOC | 2 | 
 | 1335 | Plan (stoppen roken begeleidin | LOC | 1 | 
 | R96-INF-A5 | Voorlichting omtrent effect roken | PROT | 1 | 
 | 1547 | Functie van roken voor u | LOC | 1 | 
 | 1785 | startleeftijd roken | LOC | 1 | 
 | Bent u | Bent u gestopt met roken? | LOC | 1 | 
 | 1753 | # startleeftijd roken | LOC | 1 | 
 | 3082 | Wilt u stoppen met roken? | LOC | 1 | 
 | 1511 | hypertensie roken | LOC | 1 | 
 | 2323 | Plan (stoppen roken begeleidin | LOC | 1 | 
 | ROKSTOKIN | Gestopt met roken | LOC | 1 | 
 | 1629 | # startleeftijd roken | LOC | 1 | 
 | Nog st | Nog steeds gestopt met roken | LOC | 1 | 
 | 971 | Bent u gestopt met roken? | LOC | 1 | 
 | 2150 | Wilt u stoppen met roken? | LOC | 1 | 
 | 1728 | Wilt u stoppen met roken? | LOC | 1 | 
 | 1227 | ADMI (adv:stoppen met roken) | LOC | 1 | 
 | 3085 | De nadelen van roken besproken | LOC | 1 | 
 | 972 | Bent u gestopt met roken? | LOC | 1 | 
 | ROKSTODIAB | Gestopt met roken | LOC | 1 | 
 | 1725 | De nadelen van roken besproken | LOC | 1 | 
 | 1330 | Bent u gestopt met roken? | LOC | 1 | 
 | 2148 | De nadelen van roken besproken | LOC | 1 | 
 | 1578 | Functie van roken voor u | LOC | 1 |
