### ISSUE TITLE
CONDITION_TYPE_CONCEPT_ID fro Diagnosis

### ISSUE THREAD

**Issue by ericaVoss** [mi-erasmusmc/ETL-IPCI#12]
There is now a CONCEPT_ID for conditions coming from a diagnosis.  Currently is mapped to 0 but should be mapped to:

43542353-Observation recorded from EHR

**Comment by PRijnbeek** [comment]
Yes the same is true for observations etc. we can default to those

**Comment by marcel1334** [comment]
Done
