### ISSUE TITLE
[ETL] IPCI Text vs Text OBSERVATION_SOURCE_VALUE

### ISSUE THREAD

**Issue by ericaVoss** [mi-erasmusmc/ETL-IPCI#2]
When defaulting in the OBSERVATION table, if you have IPCI TEXT put that into the CDM instead of the source text as it may be more uniform..

Example, in TEXT here is `zij rookt niet` and the IPCI TEXT `nooit`, pick the IPCI TEXT over the TEXT.

**Comment by PRijnbeek** [comment]
Not sure what you mean here.

**Comment by marcel1334** [comment]
Done
