### ISSUE TITLE
[MAPPING] Glycopyrronium Bromide

### ISSUE THREAD

**Issue by ericaVoss** [mi-erasmusmc/ETL-IPCI#5]
ATC R03BB06 - Glycopyrronium Bromide currently mapped to 43534848 but this is an ATC.  I believe it now should be mapped to 45775571,

**Comment by PRijnbeek** [comment]
This is currently mapped to 963353 Glycopyrrolate

This seems to be another name:

https://en.wikipedia.org/wiki/Glycopyrronium_bromide
