### ISSUE TITLE
[MAPPING] K86.00-Essentiï¿½le hypertensie zonder orgaanbeschadiging

### ISSUE THREAD

**Issue by ericaVoss** [mi-erasmusmc/ETL-IPCI#6]
This maps to a concept that is not invalid.

RAW VALUES
```{TEXT}
K86.00-Essentiï¿½le hypertensie zonder orgaanbeschadiging
```

STANDARD VALUES
```{TEXT}
40398391	Hypertensive disease
```

**Comment by PRijnbeek** [comment]
yes there are more like these in the old mappings. We have updated the Mappings to the latest vocab and this one should be resolved as well.
