### ISSUE TITLE
Open Heel Errors after new ETL 20170309 Eeyore version

### ISSUE THREAD

**Issue by PRijnbeek** [mi-erasmusmc/ETL-IPCI#8]
[ ] - ERROR	411-Number of condition occurrence records with end date < start date; count (n=125) should not be > 0 

[ ] - ERROR	600-Number of persons with at least one procedure occurrence, by procedure_concept_id; 19 concepts in data are not in correct vocabulary

[ ] - ERROR	700-Number of persons with at least one drug exposure, by drug_concept_id; 71 concepts in data are not in vocabulary

[ ] - ERROR	814-Number of observation records with no value (numeric, string, or concept); count (n=1,627,999) should not be > 0

I will look into examples so we can further tackle this.

**Comment by PRijnbeek** [comment]
Looked at some examples after applying the achilles heel queries. To be double checked with marcel.

**Comment by marcel1334** [comment]
All these errors come back in issue #19.
