### ISSUE TITLE
Systolic Blood Pressure

### ISSUE THREAD

**Issue by ericaVoss** [mi-erasmusmc/ETL-IPCI#9]
The code RRSYKAPS - Systolische bloeddruk (stand) should have been mapped to 30009395-Systolic Blood Pressure (supine).

The code RRSYKAMH - Systolische bloeddruk thuismeting) should have been mapped to 4187779-Average Home Systolic Blood Pressure

**Comment by PRijnbeek** [comment]
RRSYKAPS is currently mapped to 3035856 Systolic Blood Pressure Standing
RRSYKAMH is currently mapped to 3035856 Systolic Blood Pressure. I think this is fine for the current studies. You are not sure it is an average either if measured at home.
